name: "Identity Cloud"
description: "Okta's comprehensive identity and access management platform providing secure authentication, single sign-on, and user lifecycle management"
version: "2024.1"
documentation_url: "https://developer.okta.com/docs/"