name: Organization Audit Logs
description: GitHub Organizations Audit Logs tracking security-related actions including
  disabling/enabling vulnerability alerts, repository creation/deletion, and organization
  membership changes
log_type: enterprise
author: Fulcrum Technology Solutions
version: 1.0.0
product: Enterprise
vendor: GitHub
tags:
- github
- enterprise
- organization
- audit
- logs
date_created: '2025-05-16'
last_updated: '2025-05-16'
fields:
- field: action
  description: The GitHub action being performed
- field: actor
  description: The username of the actor performing the action
- field: actor_ip
  description: The IP address of the actor
- field: actor_is_bot
  description: Boolean indicating if the actor is a bot
- field: business
  description: The GitHub business name
- field: org
  description: The GitHub organization name
- field: repo
  description: The GitHub repository path (org/repo)
- field: public_repo
  description: Boolean indicating if the repository is public
- field: user_agent
  description: Browser user agent string
