vendor: claroty
product: xdome
name: xDome
description: Unified platform for comprehensive cyber-physical systems protection across OT, IoT, IIoT, IoMT, and BMS environments with asset discovery, vulnerability management, and threat detection.
version: All
documentation_url: https://docs.claroty.com/xdome/