vendor: "Microsoft Corporation"
product: "Windows"
description: "Microsoft Windows Operating System - comprehensive desktop and server platform"
version: "Multiple versions supported"
documentation_url: "https://docs.microsoft.com/en-us/windows/"