vendor: Zscaler
product: Internet Access
description: Cloud-native web security and internet access solution with advanced threat protection
version: "1.0"
documentation_url: https://help.zscaler.com/zia