# 'vendor': machine-friendly unique identifier of the parent vendor
# 'name': human-friendly product display name
vendor: paloalto
product: "GlobalProtect"
name: "GlobalProtect"
description: "Palo Alto Networks GlobalProtect VPN"
version: "All"
documentation_url: "https://docs.paloaltonetworks.com/globalprotect" 