slug: defender-for-identity
product: "Defender for Identity"
description: "Cloud-based security solution that identifies, detects, and investigates advanced threats, compromised identities, and malicious insider actions"
version: "Current"
documentation_url: "https://docs.microsoft.com/en-us/defender-for-identity/"